export const subredditMockResponse = {
    "kind": "Listing",
    "data": {
        "after": "t5_2qh03",
        "dist": 5,
        "modhash": "",
        "geo_filter": "",
        "children": [
            {
                "kind": "t5",
                "data": {
                    "user_flair_background_color": null,
                    "submit_text_html": null,
                    "restrict_posting": true,
                    "user_is_banned": null,
                    "free_form_reports": true,
                    "wiki_enabled": false,
                    "user_is_muted": null,
                    "user_can_flair_in_sr": null,
                    "display_name": "Home",
                    "header_img": null,
                    "title": "Home",
                    "allow_galleries": true,
                    "icon_size": null,
                    "primary_color": "",
                    "active_user_count": null,
                    "icon_img": "",
                    "display_name_prefixed": "r/Home",
                    "accounts_active": null,
                    "public_traffic": false,
                    "subscribers": 182686,
                    "user_flair_richtext": [],
                    "videostream_links_count": 1,
                    "name": "t5_2qs0k",
                    "quarantine": false,
                    "hide_ads": false,
                    "prediction_leaderboard_entry_type": "SUBREDDIT_HEADER",
                    "emojis_enabled": false,
                    "advertiser_category": "",
                    "public_description": "",
                    "comment_score_hide_mins": 0,
                    "allow_predictions": false,
                    "user_has_favorited": null,
                    "user_flair_template_id": null,
                    "community_icon": "",
                    "banner_background_image": "",
                    "original_content_tag_enabled": false,
                    "community_reviewed": true,
                    "submit_text": "",
                    "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Everything home related: interior design, home improvement, architecture.&lt;/p&gt;\n\n&lt;h2&gt;&lt;strong&gt;Related subreddits&lt;/strong&gt;&lt;/h2&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;a href=\"http://www.reddit.com/r/interiordesign\"&gt;/r/InteriorDesign&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"http://www.reddit.com/r/architecture\"&gt;/r/architecture&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"http://www.reddit.com/r/houseporn\"&gt;/r/houseporn&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"http://www.reddit.com/r/roomporn\"&gt;/r/roomporn&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"http://www.reddit.com/r/designmyroom\"&gt;/r/designmyroom&lt;/a&gt;&lt;/li&gt;\n&lt;/ul&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "spoilers_enabled": true,
                    "comment_contribution_settings": {
                        "allowed_media_types": null
                    },
                    "allow_talks": false,
                    "header_size": null,
                    "user_flair_position": "right",
                    "all_original_content": false,
                    "has_menu_widget": false,
                    "is_enrolled_in_new_modmail": null,
                    "key_color": "",
                    "can_assign_user_flair": true,
                    "created": 1232850357,
                    "wls": 6,
                    "show_media_preview": true,
                    "submission_type": "any",
                    "user_is_subscriber": null,
                    "allowed_media_in_comments": [],
                    "allow_videogifs": true,
                    "should_archive_posts": false,
                    "user_flair_type": "text",
                    "allow_polls": true,
                    "collapse_deleted_comments": false,
                    "emojis_custom_size": null,
                    "public_description_html": null,
                    "allow_videos": true,
                    "is_crosspostable_subreddit": false,
                    "suggested_comment_sort": null,
                    "should_show_media_in_comments_setting": true,
                    "can_assign_link_flair": true,
                    "accounts_active_is_fuzzed": false,
                    "allow_prediction_contributors": false,
                    "submit_text_label": "",
                    "link_flair_position": "right",
                    "user_sr_flair_enabled": null,
                    "user_flair_enabled_in_sr": false,
                    "allow_chat_post_creation": false,
                    "allow_discovery": true,
                    "accept_followers": true,
                    "user_sr_theme_enabled": true,
                    "link_flair_enabled": true,
                    "disable_contributor_requests": false,
                    "subreddit_type": "public",
                    "notification_level": null,
                    "banner_img": "",
                    "user_flair_text": null,
                    "banner_background_color": "",
                    "show_media": true,
                    "id": "2qs0k",
                    "user_is_contributor": null,
                    "over18": false,
                    "header_title": "",
                    "description": "Everything home related: interior design, home improvement, architecture.\n\n**Related subreddits**\n--------------------------\n* [/r/InteriorDesign](http://www.reddit.com/r/interiordesign)\n* [/r/architecture](http://www.reddit.com/r/architecture)\n* [/r/houseporn](http://www.reddit.com/r/houseporn)\n* [/r/roomporn](http://www.reddit.com/r/roomporn)\n* [/r/designmyroom](http://www.reddit.com/r/designmyroom)",
                    "is_chat_post_feature_enabled": true,
                    "submit_link_label": "",
                    "user_flair_text_color": null,
                    "restrict_commenting": false,
                    "user_flair_css_class": null,
                    "allow_images": true,
                    "lang": "en",
                    "whitelist_status": "all_ads",
                    "url": "/r/Home/",
                    "created_utc": 1232850357,
                    "banner_size": null,
                    "mobile_banner_image": "",
                    "user_is_moderator": null,
                    "allow_predictions_tournament": false
                }
            },
            {
                "kind": "t5",
                "data": {
                    "user_flair_background_color": null,
                    "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;strong&gt;AskReddit is all about DISCUSSION. Your post needs to inspire discussion, ask an open-ended question that prompts redditors to share ideas or opinions.&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Questions need to be neutral and the question alone.&lt;/strong&gt; Any opinion or answer must go as a reply to your question, this includes examples or any kind of story about you. This is so that all responses will be to your question, and there&amp;#39;s nothing else to respond to. Opinionated posts are forbidden.&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;If your question has a factual answer, try &lt;a href=\"/r/answers\"&gt;r/answers&lt;/a&gt;.&lt;/li&gt;\n&lt;li&gt;If you are trying to find out about something or get an explanation, try &lt;a href=\"/r/explainlikeimfive\"&gt;r/explainlikeimfive&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;If your question has a limited number of responses, then it&amp;#39;s not suitable.&lt;/li&gt;\n&lt;li&gt;If you&amp;#39;re asking for any kind of advice, then it&amp;#39;s not suitable.&lt;/li&gt;\n&lt;li&gt;If you feel the need to add an example in order for your question to make sense then you need to re-word your question.&lt;/li&gt;\n&lt;li&gt;If you&amp;#39;re explaining why you&amp;#39;re asking the question, you need to stop.&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;You can always ask where to post in &lt;a href=\"/r/findareddit\"&gt;r/findareddit&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "restrict_posting": true,
                    "user_is_banned": null,
                    "free_form_reports": true,
                    "wiki_enabled": true,
                    "user_is_muted": null,
                    "user_can_flair_in_sr": null,
                    "display_name": "AskReddit",
                    "header_img": "https://a.thumbs.redditmedia.com/IrfPJGuWzi_ewrDTBlnULeZsJYGz81hsSQoQJyw6LD8.png",
                    "title": "Ask Reddit...",
                    "allow_galleries": false,
                    "icon_size": [
                        256,
                        256
                    ],
                    "primary_color": "#646d73",
                    "active_user_count": null,
                    "icon_img": "https://b.thumbs.redditmedia.com/LSHrisQApf1H5F8nWShTx3_KjTOMc3R_ss3kx3XAyXQ.png",
                    "display_name_prefixed": "r/AskReddit",
                    "accounts_active": null,
                    "public_traffic": false,
                    "subscribers": 43860433,
                    "user_flair_richtext": [],
                    "name": "t5_2qh1i",
                    "quarantine": false,
                    "hide_ads": false,
                    "prediction_leaderboard_entry_type": "SUBREDDIT_HEADER",
                    "emojis_enabled": true,
                    "advertiser_category": "Lifestyles",
                    "public_description": "r/AskReddit is the place to ask and answer thought-provoking questions.",
                    "comment_score_hide_mins": 60,
                    "allow_predictions": false,
                    "user_has_favorited": null,
                    "user_flair_template_id": null,
                    "community_icon": "https://styles.redditmedia.com/t5_2qh1i/styles/communityIcon_p6kb2m6b185b1.png?width=256&amp;s=c28b9f038c305e139b62739f2133d7b776582696",
                    "banner_background_image": "",
                    "original_content_tag_enabled": false,
                    "community_reviewed": true,
                    "submit_text": "**AskReddit is all about DISCUSSION. Your post needs to inspire discussion, ask an open-ended question that prompts redditors to share ideas or opinions.**\n\n**Questions need to be neutral and the question alone.** Any opinion or answer must go as a reply to your question, this includes examples or any kind of story about you. This is so that all responses will be to your question, and there's nothing else to respond to. Opinionated posts are forbidden.\n\n* If your question has a factual answer, try r/answers.\n* If you are trying to find out about something or get an explanation, try r/explainlikeimfive\n* If your question has a limited number of responses, then it's not suitable.\n* If you're asking for any kind of advice, then it's not suitable.\n* If you feel the need to add an example in order for your question to make sense then you need to re-word your question.\n* If you're explaining why you're asking the question, you need to stop.\n\nYou can always ask where to post in r/findareddit.",
                    "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;h6&gt;&lt;a href=\"http://www.reddit.com/r/askreddit/submit?selftext=true&amp;amp;title=%5BSerious%5D\"&gt; [ SERIOUS ] &lt;/a&gt;&lt;/h6&gt;\n\n&lt;h5&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_rules\"&gt;Rules&lt;/a&gt;:&lt;/h5&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;p&gt;You must post a clear and direct question in the title. The title may contain two, short, necessary context sentences.\nNo text is allowed in the textbox. Your thoughts/responses to the question can go in the comments section. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_1-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Any post asking for advice should be generic and not specific to your situation alone. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_2-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;AskReddit is for open-ended discussion questions. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_3-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Posting, or seeking, any identifying personal information, real or fake, will result in a ban without a prior warning. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_4-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;AskReddit is not your soapbox, personal army, or advertising platform. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_5-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;[Serious] tagged posts are off-limits to jokes or irrelevant replies. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_6-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Soliciting money, goods, services, or favours is not allowed. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_7-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Mods reserve the right to remove content or restrict users&amp;#39; posting privileges as necessary if it is deemed detrimental to the subreddit or to the experience of others. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_8-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Comment replies consisting solely of images will be removed. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_9-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Do not post harmful misinformation. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index/#wiki_-rule_10-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Spam, machine-generated content, and karma farming are not permitted. &lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index/#wiki_-rule_11-\"&gt;more &amp;gt;&amp;gt;&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;h5&gt;If you think your post has disappeared, see spam or an inappropriate post, please do not hesitate to &lt;a href=\"https://www.reddit.com/message/compose?to=%2Fr%2FAskReddit\"&gt;contact the mods&lt;/a&gt;, we&amp;#39;re happy to help.&lt;/h5&gt;\n\n&lt;hr/&gt;\n\n&lt;h4&gt;Tags to use:&lt;/h4&gt;\n\n&lt;blockquote&gt;\n&lt;h2&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_6-\"&gt;[Serious]&lt;/a&gt;&lt;/h2&gt;\n&lt;/blockquote&gt;\n\n&lt;h3&gt;Use a &lt;strong&gt;[Serious]&lt;/strong&gt; post tag to designate your post as a serious, on-topic-only thread.&lt;/h3&gt;\n\n&lt;h2&gt;&lt;/h2&gt;\n\n&lt;h4&gt;Filter posts by subject:&lt;/h4&gt;\n\n&lt;p&gt;&lt;a href=\"http://ud.reddit.com/r/AskReddit/#ud\"&gt;Mod posts&lt;/a&gt;\n&lt;a href=\"https://www.reddit.com/r/AskReddit/search/?q=flair%3Aserious&amp;amp;sort=new&amp;amp;restrict_sr=on&amp;amp;t=all\"&gt;Serious posts&lt;/a&gt;\n&lt;a href=\"http://bu.reddit.com/r/AskReddit/#bu\"&gt;Megathread&lt;/a&gt;\n&lt;a href=\"http://nr.reddit.com/r/AskReddit/#nr\"&gt;Breaking news&lt;/a&gt;\n&lt;a href=\"/r/AskReddit\"&gt;Unfilter&lt;/a&gt;&lt;/p&gt;\n\n&lt;h2&gt;&lt;/h2&gt;\n\n&lt;h3&gt;Please use spoiler tags to hide spoilers. &lt;code&gt;&amp;gt;!insert spoiler here!&amp;lt;&lt;/code&gt;&lt;/h3&gt;\n\n&lt;h2&gt;&lt;/h2&gt;\n\n&lt;h4&gt;Other subreddits you might like:&lt;/h4&gt;\n\n&lt;table&gt;&lt;thead&gt;\n&lt;tr&gt;\n&lt;th align=\"left\"&gt;some&lt;/th&gt;\n&lt;th align=\"left\"&gt;header&lt;/th&gt;\n&lt;/tr&gt;\n&lt;/thead&gt;&lt;tbody&gt;\n&lt;tr&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_ask_others\"&gt;Ask Others&lt;/a&gt;&lt;/td&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_self_.26amp.3B_others\"&gt;Self &amp;amp; Others&lt;/a&gt;&lt;/td&gt;\n&lt;/tr&gt;\n&lt;tr&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_find_a_subreddit\"&gt;Find a subreddit&lt;/a&gt;&lt;/td&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_learn_something\"&gt;Learn something&lt;/a&gt;&lt;/td&gt;\n&lt;/tr&gt;\n&lt;tr&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_meta\"&gt;Meta Subs&lt;/a&gt;&lt;/td&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_what_is_this______\"&gt;What is this ___&lt;/a&gt;&lt;/td&gt;\n&lt;/tr&gt;\n&lt;tr&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_askreddit_offshoots\"&gt;AskReddit Offshoots&lt;/a&gt;&lt;/td&gt;\n&lt;td align=\"left\"&gt;&lt;a href=\"https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_offers_.26amp.3B_assistance\"&gt;Offers &amp;amp; Assistance&lt;/a&gt;&lt;/td&gt;\n&lt;/tr&gt;\n&lt;/tbody&gt;&lt;/table&gt;\n\n&lt;h2&gt;&lt;/h2&gt;\n\n&lt;h3&gt;Ever read the reddiquette? &lt;a href=\"/wiki/reddiquette\"&gt;Take a peek!&lt;/a&gt;&lt;/h3&gt;\n\n&lt;p&gt;&lt;a href=\"#/RES_SR_Config/NightModeCompatible\"&gt;&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "spoilers_enabled": true,
                    "comment_contribution_settings": {
                        "allowed_media_types": null
                    },
                    "allow_talks": false,
                    "header_size": [
                        125,
                        73
                    ],
                    "user_flair_position": "right",
                    "all_original_content": false,
                    "has_menu_widget": false,
                    "is_enrolled_in_new_modmail": null,
                    "key_color": "#222222",
                    "can_assign_user_flair": false,
                    "created": 1201233135,
                    "wls": 6,
                    "show_media_preview": true,
                    "submission_type": "self",
                    "user_is_subscriber": null,
                    "allowed_media_in_comments": [],
                    "allow_videogifs": false,
                    "should_archive_posts": true,
                    "user_flair_type": "text",
                    "allow_polls": false,
                    "collapse_deleted_comments": true,
                    "emojis_custom_size": null,
                    "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;a href=\"/r/AskReddit\"&gt;r/AskReddit&lt;/a&gt; is the place to ask and answer thought-provoking questions.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "allow_videos": false,
                    "is_crosspostable_subreddit": false,
                    "suggested_comment_sort": null,
                    "should_show_media_in_comments_setting": true,
                    "can_assign_link_flair": false,
                    "accounts_active_is_fuzzed": false,
                    "allow_prediction_contributors": false,
                    "submit_text_label": "Ask a question",
                    "link_flair_position": "right",
                    "user_sr_flair_enabled": null,
                    "user_flair_enabled_in_sr": false,
                    "allow_chat_post_creation": false,
                    "allow_discovery": true,
                    "accept_followers": true,
                    "user_sr_theme_enabled": true,
                    "link_flair_enabled": true,
                    "disable_contributor_requests": false,
                    "subreddit_type": "public",
                    "notification_level": null,
                    "banner_img": "https://b.thumbs.redditmedia.com/RdyIGEa9Ghu94wr5v3oQQ_zvE1C1cntehzZJChVFkcw.png",
                    "user_flair_text": null,
                    "banner_background_color": "#d4eaff",
                    "show_media": false,
                    "id": "2qh1i",
                    "user_is_contributor": null,
                    "over18": false,
                    "header_title": "Ass Credit",
                    "description": "###### [ [ SERIOUS ] ](http://www.reddit.com/r/askreddit/submit?selftext=true&amp;title=%5BSerious%5D)\r\n\r\n\r\n##### [Rules](https://www.reddit.com/r/AskReddit/wiki/index#wiki_rules):\r\n1. You must post a clear and direct question in the title. The title may contain two, short, necessary context sentences.\r\nNo text is allowed in the textbox. Your thoughts/responses to the question can go in the comments section. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_1-)\r\n\r\n2. Any post asking for advice should be generic and not specific to your situation alone. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_2-)\r\n\r\n3. AskReddit is for open-ended discussion questions. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_3-)\r\n\r\n4. Posting, or seeking, any identifying personal information, real or fake, will result in a ban without a prior warning. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_4-)\r\n\r\n5. AskReddit is not your soapbox, personal army, or advertising platform. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_5-)\r\n\r\n6. [Serious] tagged posts are off-limits to jokes or irrelevant replies. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_6-)\r\n\r\n7. Soliciting money, goods, services, or favours is not allowed. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_7-)\r\n\r\n8. Mods reserve the right to remove content or restrict users' posting privileges as necessary if it is deemed detrimental to the subreddit or to the experience of others. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_8-)\r\n\r\n9. Comment replies consisting solely of images will be removed. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_9-)\r\n\r\n10. Do not post harmful misinformation. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index/#wiki_-rule_10-)\r\n\r\n11. Spam, machine-generated content, and karma farming are not permitted. [more &gt;&gt;](https://www.reddit.com/r/AskReddit/wiki/index/#wiki_-rule_11-)\r\n\r\n##### If you think your post has disappeared, see spam or an inappropriate post, please do not hesitate to [contact the mods](https://www.reddit.com/message/compose?to=%2Fr%2FAskReddit), we're happy to help.\r\n\r\n---\r\n\r\n#### Tags to use:\r\n\r\n&gt; ## [[Serious]](https://www.reddit.com/r/AskReddit/wiki/index#wiki_-rule_6-)\r\n\r\n### Use a **[Serious]** post tag to designate your post as a serious, on-topic-only thread.\r\n\r\n-\r\n\r\n#### Filter posts by subject:\r\n\r\n[Mod posts](http://ud.reddit.com/r/AskReddit/#ud)\r\n[Serious posts](https://www.reddit.com/r/AskReddit/search/?q=flair%3Aserious&amp;sort=new&amp;restrict_sr=on&amp;t=all)\r\n[Megathread](http://bu.reddit.com/r/AskReddit/#bu)\r\n[Breaking news](http://nr.reddit.com/r/AskReddit/#nr)\r\n[Unfilter](/r/AskReddit)\r\n\r\n\r\n-\r\n\r\n### Please use spoiler tags to hide spoilers. `&gt;!insert spoiler here!&lt;`\r\n\r\n-\r\n\r\n#### Other subreddits you might like:\r\nsome|header\r\n:---|:---\r\n[Ask Others](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_ask_others)|[Self &amp; Others](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_self_.26amp.3B_others)\r\n[Find a subreddit](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_find_a_subreddit)|[Learn something](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_learn_something)\r\n[Meta Subs](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_meta)|[What is this ___](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_what_is_this______)\r\n[AskReddit Offshoots](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_askreddit_offshoots)|[Offers &amp; Assistance](https://www.reddit.com/r/AskReddit/wiki/sidebarsubs#wiki_offers_.26amp.3B_assistance)\r\n\r\n\r\n-\r\n\r\n### Ever read the reddiquette? [Take a peek!](/wiki/reddiquette)\r\n\r\n[](#/RES_SR_Config/NightModeCompatible)",
                    "is_chat_post_feature_enabled": true,
                    "submit_link_label": "",
                    "user_flair_text_color": null,
                    "restrict_commenting": false,
                    "user_flair_css_class": null,
                    "allow_images": false,
                    "lang": "es",
                    "whitelist_status": "all_ads",
                    "url": "/r/AskReddit/",
                    "created_utc": 1201233135,
                    "banner_size": [
                        1280,
                        384
                    ],
                    "mobile_banner_image": "",
                    "user_is_moderator": null,
                    "allow_predictions_tournament": false
                }
            },
            {
                "kind": "t5",
                "data": {
                    "user_flair_background_color": null,
                    "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;strong&gt;New Player?&lt;/strong&gt; Check out the New Player Question flair. || &lt;strong&gt;Early Access questions?&lt;/strong&gt; Check the FAQ post (under &amp;#39;See community info&amp;#39; on mobile/under &amp;#39;Hot&amp;#39; on desktop). || &lt;strong&gt;No Spoilers in Titles/Hide your Spoilers!!!&lt;/strong&gt; Use the Spoiler tag. || &lt;strong&gt;Want to post your Tav?&lt;/strong&gt; Character screenshots must be posted in the weekly Tav Tuesday Megathread. || &lt;strong&gt;Thanks for posting to &lt;a href=\"/r/BaldursGate3\"&gt;r/BaldursGate3&lt;/a&gt;!&lt;/strong&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "restrict_posting": true,
                    "user_is_banned": null,
                    "free_form_reports": true,
                    "wiki_enabled": true,
                    "user_is_muted": null,
                    "user_can_flair_in_sr": null,
                    "display_name": "BaldursGate3",
                    "header_img": null,
                    "title": "Baldur's Gate 3",
                    "allow_galleries": true,
                    "icon_size": null,
                    "primary_color": "#ddbd37",
                    "active_user_count": null,
                    "icon_img": "",
                    "display_name_prefixed": "r/BaldursGate3",
                    "accounts_active": null,
                    "public_traffic": false,
                    "subscribers": 1221050,
                    "user_flair_richtext": [],
                    "videostream_links_count": 18,
                    "name": "t5_12967t",
                    "quarantine": false,
                    "hide_ads": false,
                    "prediction_leaderboard_entry_type": "SUBREDDIT_HEADER",
                    "emojis_enabled": false,
                    "advertiser_category": "",
                    "public_description": "A community all about Baldur's Gate III, the role-playing video game by Larian Studios. BG3 is the third main game in the Baldur's Gate series. Baldur's Gate III is based on a modified version of the Dungeons &amp; Dragons 5th edition (D&amp;D 5e) tabletop RPG ruleset.\n\nGather your party and venture forth!",
                    "comment_score_hide_mins": 0,
                    "allow_predictions": false,
                    "user_has_favorited": null,
                    "user_flair_template_id": null,
                    "community_icon": "https://styles.redditmedia.com/t5_12967t/styles/communityIcon_rh7ocpigb9t51.png?width=256&amp;s=fc8ce762012139f5f4bb3fe341ec1676e175e7b3",
                    "banner_background_image": "https://styles.redditmedia.com/t5_12967t/styles/bannerBackgroundImage_2ufljuvcznmb1.jpeg?width=4000&amp;s=dca4f13fac42761ddba35fe7b6a43de5483c4800",
                    "original_content_tag_enabled": true,
                    "community_reviewed": true,
                    "submit_text": "**New Player?** Check out the New Player Question flair. || **Early Access questions?** Check the FAQ post (under 'See community info' on mobile/under 'Hot' on desktop). || **No Spoilers in Titles/Hide your Spoilers!!!** Use the Spoiler tag. || **Want to post your Tav?** Character screenshots must be posted in the weekly Tav Tuesday Megathread. || **Thanks for posting to r/BaldursGate3!**",
                    "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;A community all about &lt;em&gt;Baldur&amp;#39;s Gate III&lt;/em&gt;, the role-playing video game by Larian Studios. BG3 is the third main game in the &lt;em&gt;Baldur&amp;#39;s Gate&lt;/em&gt; series. &lt;em&gt;Baldur&amp;#39;s Gate III&lt;/em&gt; is based on a modified version of the &lt;em&gt;Dungeons &amp;amp; Dragons&lt;/em&gt; 5th edition (D&amp;amp;D 5e) tabletop RPG ruleset.&lt;/p&gt;\n\n&lt;p&gt;Gather your party and venture forth!&lt;/p&gt;\n\n&lt;h2&gt;Community Links&lt;/h2&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;a href=\"https://www.reddit.com/r/BaldursGate3/wiki/faq/\"&gt;Early Access FAQ&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://bg3.wiki/wiki/Main_Page\"&gt;Community Wiki&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://www.reddit.com/user/GameFractal/comments/1137178/gamefractalcom_character_planner_for_baldurs_gate/\"&gt;Character Planner&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://docs.google.com/spreadsheets/d/1hmY7kGPRHJjR0hjO-hVUeDef46lYowZjAHhWqR25AwE/edit#gid=1513761301\"&gt;(Spoilers) EA Relevant Items Spreadsheet&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href=\"https://www.reddit.com/r/BaldursGate3/comments/110r5bs/quick_announcement_community_links/\"&gt;updated resources&lt;/a&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;h2&gt;Rules&lt;/h2&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;strong&gt;Be civil to one another.&lt;/strong&gt; Unacceptable behaviors include name-calling, taunting, baiting, flaming, etc. The intent is for everyone to act as civil adults.&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;Respect the opinions of others.&lt;/strong&gt; Everyone&amp;#39;s perspective is unique. You don’t have to agree with them, but you also don’t have to argue or harass them about it.&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;Keep your posts relevant.&lt;/strong&gt; All submissions must be related to Baldur&amp;#39;s Gate 3. Comments should be relevant to the topic of the thread.&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;Tag spoilers and NSFW content.&lt;/strong&gt; Content that is NSFW or contains spoilers must be tagged appropriately. Additionally, titles should be free from profanity, spoilers, and other NSFW language.&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;Memes, character screenshots, and fanart must be flaired.&lt;/strong&gt; All fanart, memes, and joke posts must have proper flair. Additionally, character screenshots must be flaired with the TAV flair. Posts without it are subject to removal without warning.&lt;br/&gt;&lt;/li&gt;\n&lt;li&gt;&lt;strong&gt;No Spamming.&lt;/strong&gt; Any re-posts, low-effort posts, or posts that qualify as spam may be removed. Repeat offenders may be banned. Examples of low effort posts would be posting excessive screenshots and low effort memes&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Self-Promo Rules: Please follow Reddit&amp;#39;s guidelines for self-promo content&lt;/p&gt;\n\n&lt;p&gt;&amp;quot;For every 1 time you post self-promotional content, 9 other posts (submissions or comments) should not contain self-promotional content.&amp;quot;  &lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;strong&gt;Tav Posting&lt;/strong&gt; Character screenshots must be posted in the Tav Tuesday Megathread. Character screenshots not posted in the Megathread are subject to removal without warning.&lt;/li&gt;\n&lt;/ol&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "spoilers_enabled": true,
                    "comment_contribution_settings": {
                        "allowed_media_types": null
                    },
                    "allow_talks": false,
                    "header_size": null,
                    "user_flair_position": "right",
                    "all_original_content": false,
                    "has_menu_widget": false,
                    "is_enrolled_in_new_modmail": null,
                    "key_color": "#222222",
                    "can_assign_user_flair": true,
                    "created": 1559226938,
                    "wls": 6,
                    "show_media_preview": true,
                    "submission_type": "any",
                    "user_is_subscriber": null,
                    "allowed_media_in_comments": [],
                    "allow_videogifs": true,
                    "should_archive_posts": true,
                    "user_flair_type": "text",
                    "allow_polls": false,
                    "collapse_deleted_comments": true,
                    "emojis_custom_size": null,
                    "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;A community all about Baldur&amp;#39;s Gate III, the role-playing video game by Larian Studios. BG3 is the third main game in the Baldur&amp;#39;s Gate series. Baldur&amp;#39;s Gate III is based on a modified version of the Dungeons &amp;amp; Dragons 5th edition (D&amp;amp;D 5e) tabletop RPG ruleset.&lt;/p&gt;\n\n&lt;p&gt;Gather your party and venture forth!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "allow_videos": true,
                    "is_crosspostable_subreddit": false,
                    "suggested_comment_sort": null,
                    "should_show_media_in_comments_setting": true,
                    "can_assign_link_flair": true,
                    "accounts_active_is_fuzzed": false,
                    "allow_prediction_contributors": false,
                    "submit_text_label": "",
                    "link_flair_position": "right",
                    "user_sr_flair_enabled": null,
                    "user_flair_enabled_in_sr": false,
                    "allow_chat_post_creation": false,
                    "allow_discovery": true,
                    "accept_followers": true,
                    "user_sr_theme_enabled": true,
                    "link_flair_enabled": true,
                    "disable_contributor_requests": false,
                    "subreddit_type": "public",
                    "notification_level": null,
                    "banner_img": "",
                    "user_flair_text": null,
                    "banner_background_color": "",
                    "show_media": true,
                    "id": "12967t",
                    "user_is_contributor": null,
                    "over18": false,
                    "header_title": "Something's on my mind, well, in it.",
                    "description": "A community all about *Baldur's Gate III*, the role-playing video game by Larian Studios. BG3 is the third main game in the *Baldur's Gate* series. *Baldur's Gate III* is based on a modified version of the *Dungeons &amp; Dragons* 5th edition (D&amp;D 5e) tabletop RPG ruleset.\n\nGather your party and venture forth!\n\n## Community Links\n* [Early Access FAQ](https://www.reddit.com/r/BaldursGate3/wiki/faq/)\n* [Community Wiki](https://bg3.wiki/wiki/Main_Page)\n* [Character Planner](https://www.reddit.com/user/GameFractal/comments/1137178/gamefractalcom_character_planner_for_baldurs_gate/)\n* [(Spoilers) EA Relevant Items Spreadsheet](https://docs.google.com/spreadsheets/d/1hmY7kGPRHJjR0hjO-hVUeDef46lYowZjAHhWqR25AwE/edit#gid=1513761301)\n* [updated resources](https://www.reddit.com/r/BaldursGate3/comments/110r5bs/quick_announcement_community_links/)\n\n## Rules\n\n1. **Be civil to one another.** Unacceptable behaviors include name-calling, taunting, baiting, flaming, etc. The intent is for everyone to act as civil adults.\n2. **Respect the opinions of others.** Everyone's perspective is unique. You don’t have to agree with them, but you also don’t have to argue or harass them about it.\n3. **Keep your posts relevant.** All submissions must be related to Baldur's Gate 3. Comments should be relevant to the topic of the thread.\n4. **Tag spoilers and NSFW content.** Content that is NSFW or contains spoilers must be tagged appropriately. Additionally, titles should be free from profanity, spoilers, and other NSFW language.\n5. **Memes, character screenshots, and fanart must be flaired.** All fanart, memes, and joke posts must have proper flair. Additionally, character screenshots must be flaired with the TAV flair. Posts without it are subject to removal without warning.  \n6. **No Spamming.** Any re-posts, low-effort posts, or posts that qualify as spam may be removed. Repeat offenders may be banned. Examples of low effort posts would be posting excessive screenshots and low effort memes\n\nSelf-Promo Rules: Please follow Reddit's guidelines for self-promo content\n\n\"For every 1 time you post self-promotional content, 9 other posts (submissions or comments) should not contain self-promotional content.\"  \n\n7. **Tav Posting** Character screenshots must be posted in the Tav Tuesday Megathread. Character screenshots not posted in the Megathread are subject to removal without warning.",
                    "is_chat_post_feature_enabled": true,
                    "submit_link_label": "",
                    "user_flair_text_color": null,
                    "restrict_commenting": false,
                    "user_flair_css_class": null,
                    "allow_images": true,
                    "lang": "en",
                    "whitelist_status": "all_ads",
                    "url": "/r/BaldursGate3/",
                    "created_utc": 1559226938,
                    "banner_size": null,
                    "mobile_banner_image": "",
                    "user_is_moderator": null,
                    "allow_predictions_tournament": false
                }
            },
            {
                "kind": "t5",
                "data": {
                    "user_flair_background_color": null,
                    "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;We do not allow posts about reddit. &lt;/p&gt;\n\n&lt;p&gt;Your title should explicitly say what is mildly infuriating. and 3&lt;/p&gt;\n\n&lt;p&gt;jukmifgguggh&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "restrict_posting": true,
                    "user_is_banned": null,
                    "free_form_reports": true,
                    "wiki_enabled": true,
                    "user_is_muted": null,
                    "user_can_flair_in_sr": null,
                    "display_name": "mildlyinfuriating",
                    "header_img": "https://b.thumbs.redditmedia.com/rmlXC779KUA2MTO4r_GJd2enqa8GKx3BOasymol6gLk.png",
                    "title": "jukmifgguggh",
                    "allow_galleries": true,
                    "icon_size": [
                        256,
                        256
                    ],
                    "primary_color": "",
                    "active_user_count": null,
                    "icon_img": "https://b.thumbs.redditmedia.com/6EKfzU5PYmvE4USNgMZaBR6iCS5NnJ3YFTkZyPbXnZM.png",
                    "display_name_prefixed": "r/mildlyinfuriating",
                    "accounts_active": null,
                    "public_traffic": false,
                    "subscribers": 6630151,
                    "user_flair_richtext": [],
                    "name": "t5_2ubgg",
                    "quarantine": false,
                    "hide_ads": false,
                    "prediction_leaderboard_entry_type": "SUBREDDIT_HEADER",
                    "emojis_enabled": true,
                    "advertiser_category": "Lifestyles",
                    "public_description": "jugkfmghgug",
                    "comment_score_hide_mins": 60,
                    "allow_predictions": false,
                    "user_has_favorited": null,
                    "user_flair_template_id": null,
                    "community_icon": "https://styles.redditmedia.com/t5_2ubgg/styles/communityIcon_lkxajjefezh51.png?width=256&amp;s=7bb81fe43583d4a482979e0e54e1c14ef94ac580",
                    "banner_background_image": "https://styles.redditmedia.com/t5_2ubgg/styles/bannerBackgroundImage_qhj1ts036d811.jpg?width=4000&amp;s=9ec82657c01b5ddefb4be5b878f0a87dfe0e0418",
                    "original_content_tag_enabled": false,
                    "community_reviewed": true,
                    "submit_text": "We do not allow posts about reddit. \n\nYour title should explicitly say what is mildly infuriating. and 3\n\njukmifgguggh",
                    "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;blockquote&gt;\n&lt;p&gt;&lt;a href=\"https://td.reddit.com/r/mildlyinfuriating/#image\"&gt;&lt;/a&gt;\n&lt;a href=\"https://td.reddit.com/r/mildlyinfuriating/#button\"&gt;Enter mildyinfuriating &amp;nbsp; &amp;nbsp;( ͡° ͜ʖ ͡°)&lt;/a&gt;&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;Is your day filled with midly infuriating problems? You came to the right place then.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Rules&lt;/strong&gt;:&lt;/p&gt;\n\n&lt;p&gt;A: No reddit meta posts.&lt;/p&gt;\n\n&lt;p&gt;1) &lt;a href=\"http://www.reddit.com/r/mildlyinfuriating/comments/1exsuk/meta_modpost_new_rule_see_inside_for_details/\"&gt;No Memes or &amp;quot;meme-like&amp;quot; image macros.&lt;/a&gt; No Memes or &amp;quot;meme-like&amp;quot; image macros. These include overdone references in the title (e.g. “banana for scale”, “potato quality”, and so on).&lt;/p&gt;\n\n&lt;p&gt;8) Content requirements:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;a) Please try to post original content. Reposts or crossposts of someone else&amp;#39;s content will be removed if it has been posted on Reddit within the past 6 months. At the moderator&amp;#39;s discretion, content posted without the author&amp;#39;s original consent or without linking to an original source will also be removed.&lt;/li&gt;\n&lt;li&gt;b) No GIFs that end slightly before something happens (&lt;a href=\"http://i.imgur.com/Lq6m5QY.gifv\"&gt;Example&lt;/a&gt;)&lt;/li&gt;\n&lt;li&gt;c) Unn&lt;sup&gt;ecessarily&lt;/sup&gt; overdone &lt;sup&gt;text,&lt;/sup&gt; ar&amp;rarr;rows, scribbles, or substantive edits over the original content are not allowed.&lt;/li&gt;\n&lt;li&gt;d) No posting surveys - posts about surveys are allowed, however bear in mind they are often overdone.&lt;/li&gt;\n&lt;li&gt;f) Blur out any personal information. (Full names, phone numbers, license plates etc.)&lt;/li&gt;\n&lt;li&gt;f) R3: Respect Reddiquette and Follow Reddit Rules&lt;/li&gt;\n&lt;li&gt;g) R4: No grandstanding, politics, or pushing agendas. No meta reddit posts.\nThis includes posts that could be, within reason, regarded as politically, sexually, racially, or socially inappropriate or unnecessary. (&lt;a href=\"https://i.imgur.com/Um3eIs7.jpg\"&gt;Example&lt;/a&gt;). Posts that push an agenda of any sort is also prohibited, including inappropriate posts about this subreddit or other subs as described in &amp;quot;prevent brigading&amp;quot; rule. If you&amp;#39;re unsure if your post or comment falls under this rule, message the mods to ask!\n4) R5: Prevent brigading, including using &amp;quot;np&amp;quot; links for Reddit&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;6) Prevent brigading. Mentioning subreddits is fine; talking about them in a negative way is not - Use modmail for disputes, not posts. Also, when posting links to reddit in comments, please use &lt;sup&gt;[np.reddit.com](np.reddit.com)&lt;/sup&gt; formatting in order to prevent brigading.&lt;/p&gt;\n\n&lt;p&gt;These rules are &lt;strong&gt;subject to the moderator&amp;#39;s discretion&lt;/strong&gt;, and can change at any time. A full, in-dpeth explanation can be found in the wiki &lt;a href=\"https://www.reddit.com/r/mildlyinfuriating/about/rules\"&gt;here&lt;/a&gt;.&lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;Repeated violation of rules may result in banning&lt;/em&gt;&lt;/p&gt;\n\n&lt;p&gt;3) Added emphasis on rule 8g: NO POLITICS&lt;/p&gt;\n\n&lt;p&gt;7) &lt;a href=\"/u/dnanf\"&gt;/u/dnanf&lt;/a&gt; may post whatever he wants, even if it&amp;#39;s shit. It is your duty as a good redditor to upvote his posts.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;The Mild Network:&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyAmusing\"&gt;/r/MildlyAmusing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyAwesome\"&gt;/r/MildlyAwesome&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyAww\"&gt;r/MildlyAww&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyBestOf\"&gt;/r/MildlyBestOf&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyConfusing\"&gt;/r/MildlyConfusing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyCreepy\"&gt;/r/MildlyCreepy&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyDangerous\"&gt;r/MildlyDangerous&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyDepressing\"&gt;/r/MildlyDepressing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyDisgusting\"&gt;/r/MildlyDisgusting&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyDisturbing\"&gt;/r/MildlyDisturbing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyEnteristing\"&gt;/r/MildlyEnteristing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyImpressive\"&gt;/r/MildlyImpressive&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyMotivated\"&gt;/r/MildlyMotivated&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyInteresting\"&gt;/r/MildlyInteresting&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyInterestingIAmA\"&gt;r/MildlyInterestingIAmA&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyInterestingMC\"&gt;/r/MildlyInterestingMC&lt;/a&gt; (Minecraft)&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyMetal\"&gt;/r/MildlyMetal&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyOffensive\"&gt;/r/MildlyOffensive&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyPleasing\"&gt;/r/MildlyPleasing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlySatisfying\"&gt;/r/MildlySatisfying&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyStartledCats\"&gt;/r/MildlyStartledCats&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyStupid\"&gt;r/MildlyStupid&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyUninteresting\"&gt;/r/MildlyUninteresting&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyWeird\"&gt;/r/MildlyWeird&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/MildlyWTF\"&gt;/r/MildlyWTF&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;&lt;strong&gt;Our Friends:&lt;/strong&gt;&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/extremelyinfuriating\"&gt;/r/extremelyinfuriating&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/gifsthatendtoosoon\"&gt;/r/gifsthatendtoosoon&lt;/a&gt; &lt;strong&gt;NEW: Please post gifs that end too soon in that sub, instead of here.&lt;/strong&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/QuestionCollege\"&gt;/r/QuestionCollege&lt;/a&gt; &lt;strong&gt;NEW&lt;/strong&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/UnnecessaryQuotes\"&gt;/r/UnnecessaryQuotes&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/PerfectFit\"&gt;/r/PerfectFit&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/FakeRedditNews\"&gt;/r/FakeRedditNews&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/OddlySatisfying\"&gt;/r/OddlySatisfying&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/SlightlyUnsatisfying\"&gt;/r/SlightlyUnsatisfying&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/FunnyAndSad\"&gt;/r/FunnyAndSad&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Today_I_Realized\"&gt;r/Today_I_Realized&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/WellThatSucks\"&gt;/r/WellThatSucks&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/BadParking\"&gt;/r/BadParking&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/BloodFueledRage\"&gt;r/BloodFueledRage&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Rage\"&gt;/r/Rage&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Infuriating\"&gt;/r/Infuriating&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Amusing\"&gt;/r/Amusing&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/BenignExistence\"&gt;/r/BenignExistence&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/CasualIAmA\"&gt;/r/CasualIAmA&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/InterestingAnecdote\"&gt;/r/InterestingAnecdote&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/GrindsMyGears\"&gt;/r/GrindsMyGears&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/HowToNotGiveaFuck\"&gt;/r/HowToNotGiveaFuck&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/NotQuiteWTF\"&gt;/r/NotQuiteWTF&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Onejob\"&gt;/r/Onejob&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/Vastlystupid\"&gt;/r/Vastlystupid&lt;/a&gt; &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/PleaseJustStop\"&gt;/r/PleaseJustStop&lt;/a&gt;  &lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"/r/BadYTAds\"&gt;/r/BadYTAds&lt;/a&gt;  &lt;/p&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;&lt;a href=\"http://www.reddit.com/r/mildlyinteresting/comments/zytpk/list_of_similar_subreddits_and_mild_network/\"&gt;More mildly related subreddits&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"http://www.reddit.com/r/mildlyinfuriating/comments/17nzkh/meta_announcement_new_flair_options/\"&gt;Click Here&lt;/a&gt; for details about flair!&lt;/p&gt;\n\n&lt;h2&gt;&lt;a href=\"http://www.reddit.com/r/mildlyinfuriating/new\"&gt;New Posts&lt;/a&gt;&lt;/h2&gt;\n\n&lt;p&gt;&lt;a href=\"/r/simulated\" title=\"This is the best /r/simulated has to offer\"&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"https://www.reddit.com/r/mildlyinfuriating/comments/dzlehu/congrats_on_2_million_here_is_the_double#sidebar\"&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"#ad1\"&gt;test&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;jukmifgguggh&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"https://www.battleforthenet.com/\" title=\"COME ON!! CLICK IT! DOOOOOO ITTTTTT\"&gt;💰💰💰 Nothing💸is💸more💸infuriating💸than💸restricted💸internet 💰💰💰&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"https://redd.it/82yfzr\" title=\"What are you doing over there?\"&gt;&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;a href=\"#youtube-footer\"&gt;&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "spoilers_enabled": true,
                    "comment_contribution_settings": {
                        "allowed_media_types": [
                            "expression",
                            "giphy"
                        ]
                    },
                    "allow_talks": false,
                    "header_size": [
                        73,
                        81
                    ],
                    "user_flair_position": "right",
                    "all_original_content": false,
                    "has_menu_widget": false,
                    "is_enrolled_in_new_modmail": null,
                    "key_color": "#ff8717",
                    "can_assign_user_flair": true,
                    "created": 1339961663,
                    "wls": 6,
                    "show_media_preview": true,
                    "submission_type": "any",
                    "user_is_subscriber": null,
                    "allowed_media_in_comments": [
                        "expression",
                        "giphy"
                    ],
                    "allow_videogifs": true,
                    "should_archive_posts": true,
                    "user_flair_type": "text",
                    "allow_polls": false,
                    "collapse_deleted_comments": false,
                    "emojis_custom_size": null,
                    "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;jugkfmghgug&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "allow_videos": false,
                    "is_crosspostable_subreddit": false,
                    "suggested_comment_sort": null,
                    "should_show_media_in_comments_setting": true,
                    "can_assign_link_flair": false,
                    "accounts_active_is_fuzzed": false,
                    "allow_prediction_contributors": false,
                    "submit_text_label": "",
                    "link_flair_position": "right",
                    "user_sr_flair_enabled": null,
                    "user_flair_enabled_in_sr": false,
                    "allow_chat_post_creation": false,
                    "allow_discovery": true,
                    "accept_followers": true,
                    "user_sr_theme_enabled": true,
                    "link_flair_enabled": true,
                    "disable_contributor_requests": true,
                    "subreddit_type": "public",
                    "notification_level": null,
                    "banner_img": "",
                    "user_flair_text": null,
                    "banner_background_color": "#ff8717",
                    "show_media": true,
                    "id": "2ubgg",
                    "user_is_contributor": null,
                    "over18": false,
                    "header_title": "jukmifgguggh",
                    "description": "&gt;[](https://td.reddit.com/r/mildlyinfuriating/#image)\n[Enter mildyinfuriating &amp;nbsp; &amp;nbsp;( ͡° ͜ʖ ͡°)](https://td.reddit.com/r/mildlyinfuriating/#button)\n\nIs your day filled with midly infuriating problems? You came to the right place then.\n\n**Rules**:\n\nA: No reddit meta posts.\n\n1) [No Memes or \"meme-like\" image macros.](http://www.reddit.com/r/mildlyinfuriating/comments/1exsuk/meta_modpost_new_rule_see_inside_for_details/) No Memes or \"meme-like\" image macros. These include overdone references in the title (e.g. “banana for scale”, “potato quality”, and so on).\n\n8) Content requirements:\n\n* a) Please try to post original content. Reposts or crossposts of someone else's content will be removed if it has been posted on Reddit within the past 6 months. At the moderator's discretion, content posted without the author's original consent or without linking to an original source will also be removed.\n* b) No GIFs that end slightly before something happens ([Example](http://i.imgur.com/Lq6m5QY.gifv))\n* c) Unn^ecessarily overdone ^text, ar&amp;rarr;rows, scribbles, or substantive edits over the original content are not allowed.\n* d) No posting surveys - posts about surveys are allowed, however bear in mind they are often overdone.\n* f) Blur out any personal information. (Full names, phone numbers, license plates etc.)\n* f) R3: Respect Reddiquette and Follow Reddit Rules\n* g) R4: No grandstanding, politics, or pushing agendas. No meta reddit posts.\n This includes posts that could be, within reason, regarded as politically, sexually, racially, or socially inappropriate or unnecessary. ([Example](https://i.imgur.com/Um3eIs7.jpg)). Posts that push an agenda of any sort is also prohibited, including inappropriate posts about this subreddit or other subs as described in \"prevent brigading\" rule. If you're unsure if your post or comment falls under this rule, message the mods to ask!\n4) R5: Prevent brigading, including using \"np\" links for Reddit\n\n6) Prevent brigading. Mentioning subreddits is fine; talking about them in a negative way is not - Use modmail for disputes, not posts. Also, when posting links to reddit in comments, please use ^[np.reddit.com](np.reddit.com) formatting in order to prevent brigading.\n\nThese rules are **subject to the moderator's discretion**, and can change at any time. A full, in-dpeth explanation can be found in the wiki [here](https://www.reddit.com/r/mildlyinfuriating/about/rules).\n\n*Repeated violation of rules may result in banning*\n\n3) Added emphasis on rule 8g: NO POLITICS\n\n7) /u/dnanf may post whatever he wants, even if it's shit. It is your duty as a good redditor to upvote his posts.\n\n\n\n\n**The Mild Network:**\n\n* /r/MildlyAmusing\n\n* /r/MildlyAwesome\n\n* r/MildlyAww\n\n* /r/MildlyBestOf\n\n* /r/MildlyConfusing\n\n* /r/MildlyCreepy\n\n* r/MildlyDangerous\n\n* /r/MildlyDepressing\n\n* /r/MildlyDisgusting\n\n* /r/MildlyDisturbing\n\n* /r/MildlyEnteristing\n\n* /r/MildlyImpressive\n\n* /r/MildlyMotivated\n\n* /r/MildlyInteresting\n\n* r/MildlyInterestingIAmA\n\n* /r/MildlyInterestingMC (Minecraft)\n\n* /r/MildlyMetal \n\n* /r/MildlyOffensive\n\n* /r/MildlyPleasing\n\n* /r/MildlySatisfying\n\n* /r/MildlyStartledCats \n\n* r/MildlyStupid\n\n* /r/MildlyUninteresting\n\n* /r/MildlyWeird\n\n* /r/MildlyWTF\n\n**Our Friends:**\n\n* /r/extremelyinfuriating \n\n* /r/gifsthatendtoosoon **NEW: Please post gifs that end too soon in that sub, instead of here.**\n\n* /r/QuestionCollege **NEW**\n\n* /r/UnnecessaryQuotes\n\n* /r/PerfectFit\n\n* /r/FakeRedditNews\n\n* /r/OddlySatisfying\n\n* /r/SlightlyUnsatisfying\n\n* /r/FunnyAndSad\n\n* r/Today_I_Realized\n\n* /r/WellThatSucks \n\n* /r/BadParking \n\n* r/BloodFueledRage\n\n* /r/Rage\n\n* /r/Infuriating\n\n* /r/Amusing\n\n* /r/BenignExistence\n\n* /r/CasualIAmA\n\n* /r/InterestingAnecdote\n\n* /r/GrindsMyGears\n\n* /r/HowToNotGiveaFuck\n\n* /r/NotQuiteWTF\n\n* /r/Onejob\n\n* /r/Vastlystupid \n\n* /r/PleaseJustStop  \n\n* /r/BadYTAds  \n\n[More mildly related subreddits](http://www.reddit.com/r/mildlyinteresting/comments/zytpk/list_of_similar_subreddits_and_mild_network/)\n\n[Click Here](http://www.reddit.com/r/mildlyinfuriating/comments/17nzkh/meta_announcement_new_flair_options/) for details about flair!\n\n\n##[New Posts](http://www.reddit.com/r/mildlyinfuriating/new)##\n\n\n[](/r/simulated 'This is the best /r/simulated has to offer')\n\n[](https://www.reddit.com/r/mildlyinfuriating/comments/dzlehu/congrats_on_2_million_here_is_the_double#sidebar)\n\n[test](#ad1)\n\njukmifgguggh\n\n[💰💰💰 Nothing💸is💸more💸infuriating💸than💸restricted💸internet 💰💰💰](https://www.battleforthenet.com/ \"COME ON!! CLICK IT! DOOOOOO ITTTTTT\")\n\n[](https://redd.it/82yfzr \"What are you doing over there?\")\n\n[](#youtube-footer)",
                    "is_chat_post_feature_enabled": true,
                    "submit_link_label": "Submit your mild infuriation jukmifgguggh",
                    "user_flair_text_color": null,
                    "restrict_commenting": false,
                    "user_flair_css_class": null,
                    "allow_images": true,
                    "lang": "en",
                    "whitelist_status": "all_ads",
                    "url": "/r/mildlyinfuriating/",
                    "created_utc": 1339961663,
                    "banner_size": null,
                    "mobile_banner_image": "",
                    "user_is_moderator": null,
                    "allow_predictions_tournament": false
                }
            },
            {
                "kind": "t5",
                "data": {
                    "user_flair_background_color": null,
                    "submit_text_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;h1&gt;This is an ALL AGES sub. Posting explicit content WILL get you a ban.&lt;/h1&gt;\n\n&lt;h1&gt;ALL MEMES MUST BE GAMING-RELATED, NON-GAMING TEMPLATES SUCH AS SPONGEBOB, &amp;quot;CHANGE MY MIND&amp;quot; ETC. WILL BE REMOVED&lt;/h1&gt;\n\n&lt;h1&gt;IF YOU ARE POSTING AN OPEN-ENDED, ASKREDDIT STYLE QUESTION (EG: &amp;quot;WHAT IS YOUR FAVORITE CHILDHOOD GAME?&amp;quot;), IT MUST BE A TEXT POST. IMAGE POST VERSIONS ARE NOT ALLOWED.&lt;/h1&gt;\n\n&lt;p&gt;Please keep in mind the rest of &lt;a href=\"https://www.reddit.com/r/gaming/about/rules\"&gt;our rules&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "restrict_posting": true,
                    "user_is_banned": null,
                    "free_form_reports": false,
                    "wiki_enabled": true,
                    "user_is_muted": null,
                    "user_can_flair_in_sr": null,
                    "display_name": "gaming",
                    "header_img": "https://b.thumbs.redditmedia.com/O5WuUhVrdQSH52J-W42Kp6TCWdDviUQP8KjqgTzXZ4k.png",
                    "title": "r/gaming",
                    "allow_galleries": false,
                    "icon_size": [
                        256,
                        256
                    ],
                    "primary_color": "#333335",
                    "active_user_count": null,
                    "icon_img": "https://b.thumbs.redditmedia.com/0PgZl68jAxA6T1BH6uvUQ5Bz1F1GrrJLCL8oi2Gz0Ak.png",
                    "display_name_prefixed": "r/gaming",
                    "accounts_active": null,
                    "public_traffic": false,
                    "subscribers": 38706166,
                    "user_flair_richtext": [],
                    "name": "t5_2qh03",
                    "quarantine": false,
                    "hide_ads": false,
                    "prediction_leaderboard_entry_type": "SUBREDDIT_HEADER",
                    "emojis_enabled": true,
                    "advertiser_category": "Games",
                    "public_description": "The Number One Gaming forum on the Internet.",
                    "comment_score_hide_mins": 10,
                    "allow_predictions": false,
                    "user_has_favorited": null,
                    "user_flair_template_id": null,
                    "community_icon": "https://styles.redditmedia.com/t5_2qh03/styles/communityIcon_1isvxgkk7hw51.png?width=256&amp;s=b2c4017083ea0176a3dd4837f6e009bbc8384f15",
                    "banner_background_image": "https://styles.redditmedia.com/t5_2qh03/styles/bannerBackgroundImage_j84aqdq3eyd91.png?width=4000&amp;s=750c0c8fac9a435d86f5884c01db442811a2c90d",
                    "original_content_tag_enabled": false,
                    "community_reviewed": true,
                    "submit_text": "#This is an ALL AGES sub. Posting explicit content WILL get you a ban.\n\n#ALL MEMES MUST BE GAMING-RELATED, NON-GAMING TEMPLATES SUCH AS SPONGEBOB, \"CHANGE MY MIND\" ETC. WILL BE REMOVED\n\n#IF YOU ARE POSTING AN OPEN-ENDED, ASKREDDIT STYLE QUESTION (EG: \"WHAT IS YOUR FAVORITE CHILDHOOD GAME?\"), IT MUST BE A TEXT POST. IMAGE POST VERSIONS ARE NOT ALLOWED.\n\nPlease keep in mind the rest of [our rules](https://www.reddit.com/r/gaming/about/rules)",
                    "description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;&lt;strong&gt;If your submission does not appear, do not delete it. Simply &lt;a href=\"https://www.reddit.com/message/compose?to=%2Fr%2Fgaming\"&gt;message the moderators&lt;/a&gt; and ask us to look into it.&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Please note, you are required to have some &lt;a href=\"/r/gaming\"&gt;r/gaming&lt;/a&gt; Community Karma to make a post. Please comment around before posting.&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;&lt;em&gt;Do NOT private message or use reddit chat to contact moderators about moderator actions. Only message the team via the link above. Directly messaging individual moderators may result in a temporary ban.&lt;/em&gt;&lt;/p&gt;\n\n&lt;hr/&gt;\n\n&lt;h1&gt;Community Rules&lt;/h1&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;p&gt;&lt;strong&gt;Submissions must be directly gaming-related&lt;/strong&gt;, not just a &amp;quot;forced&amp;quot; connection via the title or a caption added to the content.  Note that we do not allow non-gaming meme templates as submissions.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Posting guidelines: No bandwagon/raid/&amp;quot;pass it on&amp;quot; or direct reply posts, Posts must be in English, Pictures of children may be removed due to safety concerns, No &amp;quot;ragebait&amp;quot; posts&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;No piracy, even &amp;quot;abandonware&amp;quot;.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Mark your spoilers and NSFW submissions, comments and links. Spoiler tags are &lt;code&gt;&amp;gt;!X kills Y!&amp;lt;&lt;/code&gt;  . Cosplay posts from content creators who focus primarily is adult content will be removed.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;No Giveaways / Trades / Contests / Items for sale / Donation Requests / Crypto anything&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Submit only the original source of the content. No general URL shorteners (bitly, tinyurl, etc). No screenshots of websites or Twitter.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;&lt;a href=\"https://www.reddit.com/r/gaming/wiki/index#wiki_rule_7.3A_self-promotion\"&gt;&lt;strong&gt;Follow the rules of promotion.&lt;/strong&gt;&lt;/a&gt; \n&lt;strong&gt;This is not the place to spam your channel or stream.&lt;/strong&gt; No referral, affiliate, livestream, and/or survey links.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Discussion Prompts must be submitted as self/text posts, not as image posts.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;Posts and comments, whether in jest or with malice, that contain racist, sexist, homophobic content, threats, or other forms of toxicity will be removed, regardless of popularity or relevance.&lt;/p&gt;&lt;/li&gt;\n&lt;li&gt;&lt;p&gt;For AMA rules, &lt;a href=\"https://www.reddit.com/r/gaming/wiki/ama\"&gt;&lt;strong&gt;click here&lt;/strong&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;h2&gt;&lt;a href=\"http://www.reddit.com/r/gaming/wiki/index\"&gt;For a more detailed explanation of these rules, click here.&lt;/a&gt;&lt;/h2&gt;\n\n&lt;h2&gt;&lt;a href=\"http://www.reddit.com/r/gaming/wiki/faq\"&gt;Click here for a list of other gaming subreddits.&lt;/a&gt;&lt;/h2&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "spoilers_enabled": true,
                    "comment_contribution_settings": {
                        "allowed_media_types": [
                            "expression"
                        ]
                    },
                    "allow_talks": false,
                    "header_size": [
                        163,
                        112
                    ],
                    "user_flair_position": "right",
                    "all_original_content": false,
                    "has_menu_widget": false,
                    "is_enrolled_in_new_modmail": null,
                    "key_color": "#222222",
                    "can_assign_user_flair": true,
                    "created": 1190054605,
                    "wls": 6,
                    "show_media_preview": true,
                    "submission_type": "any",
                    "user_is_subscriber": null,
                    "allowed_media_in_comments": [
                        "expression"
                    ],
                    "allow_videogifs": true,
                    "should_archive_posts": true,
                    "user_flair_type": "text",
                    "allow_polls": false,
                    "collapse_deleted_comments": true,
                    "emojis_custom_size": null,
                    "public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;The Number One Gaming forum on the Internet.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
                    "allow_videos": false,
                    "is_crosspostable_subreddit": false,
                    "suggested_comment_sort": null,
                    "should_show_media_in_comments_setting": true,
                    "can_assign_link_flair": false,
                    "accounts_active_is_fuzzed": false,
                    "allow_prediction_contributors": false,
                    "submit_text_label": "",
                    "link_flair_position": "left",
                    "user_sr_flair_enabled": null,
                    "user_flair_enabled_in_sr": false,
                    "allow_chat_post_creation": false,
                    "allow_discovery": true,
                    "accept_followers": true,
                    "user_sr_theme_enabled": true,
                    "link_flair_enabled": true,
                    "disable_contributor_requests": true,
                    "subreddit_type": "public",
                    "notification_level": null,
                    "banner_img": "",
                    "user_flair_text": null,
                    "banner_background_color": "#373c3f",
                    "show_media": true,
                    "id": "2qh03",
                    "user_is_contributor": null,
                    "over18": false,
                    "header_title": "",
                    "description": "**If your submission does not appear, do not delete it. Simply [message the moderators](https://www.reddit.com/message/compose?to=%2Fr%2Fgaming) and ask us to look into it.**\n\n**Please note, you are required to have some r/gaming Community Karma to make a post. Please comment around before posting.**\n\n*Do NOT private message or use reddit chat to contact moderators about moderator actions. Only message the team via the link above. Directly messaging individual moderators may result in a temporary ban.*\n\n\n\n---\n#Community Rules\n\n1. **Submissions must be directly gaming-related**, not just a \"forced\" connection via the title or a caption added to the content.  Note that we do not allow non-gaming meme templates as submissions.\n\n1. Posting guidelines: No bandwagon/raid/\"pass it on\" or direct reply posts, Posts must be in English, Pictures of children may be removed due to safety concerns, No \"ragebait\" posts\n\n1. No piracy, even \"abandonware\".\n\n1. Mark your spoilers and NSFW submissions, comments and links. Spoiler tags are `&gt;!X kills Y!&lt;`  . Cosplay posts from content creators who focus primarily is adult content will be removed.\n\n1. No Giveaways / Trades / Contests / Items for sale / Donation Requests / Crypto anything\n\n1. Submit only the original source of the content. No general URL shorteners (bitly, tinyurl, etc). No screenshots of websites or Twitter.\n\n1. [**Follow the rules of promotion.**](https://www.reddit.com/r/gaming/wiki/index#wiki_rule_7.3A_self-promotion) \n**This is not the place to spam your channel or stream.** No referral, affiliate, livestream, and/or survey links.\n\n1. Discussion Prompts must be submitted as self/text posts, not as image posts.\n\n1. Posts and comments, whether in jest or with malice, that contain racist, sexist, homophobic content, threats, or other forms of toxicity will be removed, regardless of popularity or relevance.\n\n1. For AMA rules, [**click here**](https://www.reddit.com/r/gaming/wiki/ama).\n\n\n##[For a more detailed explanation of these rules, click here.](http://www.reddit.com/r/gaming/wiki/index)\n\n\n##[Click here for a list of other gaming subreddits.](http://www.reddit.com/r/gaming/wiki/faq)",
                    "is_chat_post_feature_enabled": true,
                    "submit_link_label": "",
                    "user_flair_text_color": null,
                    "restrict_commenting": false,
                    "user_flair_css_class": null,
                    "allow_images": true,
                    "lang": "en",
                    "whitelist_status": "all_ads",
                    "url": "/r/gaming/",
                    "created_utc": 1190054605,
                    "banner_size": null,
                    "mobile_banner_image": "",
                    "user_is_moderator": null,
                    "allow_predictions_tournament": false
                }
            }
        ],
        "before": null
    }
}